DROP TABLE IF EXISTS unsolvedPuzzle;
DROP TABLE IF EXISTS solvedPuzzle;

CREATE TABLE unsolvedPuzzle (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    row1 VARCHAR(512) NOT NULL,
    row2 VARCHAR(512) NOT NULL,
    row3 VARCHAR(512) NOT NULL,
    row4 VARCHAR(512) NOT NULL,
    row5 VARCHAR(512) NOT NULL,
    row6 VARCHAR(512) NOT NULL,
    row7 VARCHAR(512) NOT NULL,
    row8 VARCHAR(512) NOT NULL,
    row9 VARCHAR(512) NOT NULL
);

CREATE TABLE solvedPuzzle (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    row1 VARCHAR(512) NOT NULL,
    row2 VARCHAR(512) NOT NULL,
    row3 VARCHAR(512) NOT NULL,
    row4 VARCHAR(512) NOT NULL,
    row5 VARCHAR(512) NOT NULL,
    row6 VARCHAR(512) NOT NULL,
    row7 VARCHAR(512) NOT NULL,
    row8 VARCHAR(512) NOT NULL,
    row9 VARCHAR(512) NOT NULL
);