DROP TABLE IF EXISTS row1;
DROP TABLE IF EXISTS row2;
DROP TABLE IF EXISTS row3;
DROP TABLE IF EXISTS row4;
DROP TABLE IF EXISTS row5;
DROP TABLE IF EXISTS row6;
DROP TABLE IF EXISTS row7;
DROP TABLE IF EXISTS row8;
DROP TABLE IF EXISTS row9;

CREATE TABLE row1 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL,
);
CREATE TABLE row2 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL,
);
CREATE TABLE row3 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL,
);
CREATE TABLE row4 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL,
);
CREATE TABLE row5 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL,
);
CREATE TABLE row6 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL,
);
CREATE TABLE row7 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL,
);
CREATE TABLE row8 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL,
);
CREATE TABLE row9 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL,
);